-- MySQL Script generated by MySQL Workbench
-- qui 01 jun 2023 20:49:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema distribuidora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `distribuidora` ;

-- -----------------------------------------------------
-- Schema distribuidora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `distribuidora` ;
USE `distribuidora` ;

-- -----------------------------------------------------
-- Table `distribuidora`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distribuidora`.`usuario` ;

CREATE TABLE IF NOT EXISTS `distribuidora`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(19) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `login` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `CPF_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `LOGIN_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distribuidora`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `distribuidora`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `distribuidora`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `distribuidora`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distribuidora`.`cliente` ;

CREATE TABLE IF NOT EXISTS `distribuidora`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `distribuidora`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distribuidora`.`entrega` ;

CREATE TABLE IF NOT EXISTS `distribuidora`.`entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `observacao` VARCHAR(200) NULL,
  `situacao` ENUM('ENTREGUE', 'PENDENTE') NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entrega_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `distribuidora`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`mercadoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distribuidora`.`mercadoria` ;

CREATE TABLE IF NOT EXISTS `distribuidora`.`mercadoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distribuidora`.`item` ;

CREATE TABLE IF NOT EXISTS `distribuidora`.`item` (
  `entrega_id` INT NOT NULL,
  `mercadoria_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`entrega_id`, `mercadoria_id`),
  INDEX `fk_entrega_has_mercadoria_mercadoria1_idx` (`mercadoria_id` ASC) VISIBLE,
  INDEX `fk_entrega_has_mercadoria_entrega_idx` (`entrega_id` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_has_mercadoria_entrega`
    FOREIGN KEY (`entrega_id`)
    REFERENCES `distribuidora`.`entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_has_mercadoria_mercadoria1`
    FOREIGN KEY (`mercadoria_id`)
    REFERENCES `distribuidora`.`mercadoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `usuario` (`id`, `nome`, `cpf`, `data_nascimento`, `telefone`, `email`, `endereco`, `login`, `senha`) VALUES
(1,	'Admin',	'999.999.999-99',	'2000-01-01',	'(99)99999-9999',	'admin@admin.com',	'Rua',	'admin',	'$2y$10$t/d0fdUvCb5MWqFNLiEZL.P/PWHecdnefZrEbBRBheiCqGJD6a1Ie');
INSERT INTO `funcionario` (`id`, `cargo`, `usuario_id`) VALUES
(1,	'Diretor',	1);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
